# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitHooks < Formula
  desc ""
  homepage "https://github.com/lvrach/git-hooks/"
  version "0.1.5"

  depends_on "gitleaks" => :optional

  on_macos do
    on_intel do
      url "https://github.com/lvrach/git-hooks/releases/download/v0.1.5/git-hooks_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "f5d4510dd6aa7307449d3c49e11a47e5810b45725b49a164a97af5211801f30c"

      def install
        bin.install "git-hooks"
      end
    end
    on_arm do
      url "https://github.com/lvrach/git-hooks/releases/download/v0.1.5/git-hooks_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "2fe6eda3d5a6fe802af38209558776b778131ed8b95fe250b5d8e4423393e7e5"

      def install
        bin.install "git-hooks"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvrach/git-hooks/releases/download/v0.1.5/git-hooks_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "d7d0aca3e51ab4c90fe6713a4ff7f2601a980ca2fbb884ad4d2b2789979ce2f2"

        def install
          bin.install "git-hooks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvrach/git-hooks/releases/download/v0.1.5/git-hooks_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "fa4b0bbedeac25dee1f57c8fc7a64318548d8dcd0a506eaef27acd6aadb8fc48"

        def install
          bin.install "git-hooks"
        end
      end
    end
  end

  test do
    system "#{bin}/git-hooks"
  end
end
