# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitHooks < Formula
  desc ""
  homepage "https://github.com/lvrach/git-hooks/"
  version "0.1.4"

  depends_on "git"
  depends_on "gitleaks" => :optional

  on_macos do
    on_intel do
      url "https://github.com/lvrach/git-hooks/releases/download/v0.1.4/git-hooks_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "e0c0d2efd03dd59b0e5107a19a4df5f0b32404ada76aaa03f8d472f24062029c"

      def install
        bin.install "git-hooks"
      end
    end
    on_arm do
      url "https://github.com/lvrach/git-hooks/releases/download/v0.1.4/git-hooks_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "3f6affd067a437b2ac5e456097ada1e27b036ff5137719fbc18e222e6e963308"

      def install
        bin.install "git-hooks"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvrach/git-hooks/releases/download/v0.1.4/git-hooks_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "a6ac75811f9ba968c600a957f041e6cf574ae1aaf0179b24a0e4a1620bf976c4"

        def install
          bin.install "git-hooks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvrach/git-hooks/releases/download/v0.1.4/git-hooks_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "a1f8bebd07222d1e31ddc1473045c106ae196e6e56970bf08ef95f563bc54020"

        def install
          bin.install "git-hooks"
        end
      end
    end
  end

  test do
    system "#{bin}/git-hooks"
  end
end
