# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitHooks < Formula
  desc ""
  homepage "https://github.com/lvrach/git-hooks/"
  version "0.0.1-rc-5"

  depends_on "git" if OS.mac?
  depends_on "zsh" => :optional

  on_macos do
    on_intel do
      url "https://github.com/lvrach/git-hooks/releases/download/v0.0.1-rc-5/git-hooks_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "50672004cd55251949fe3c227f0996949f0b475c47e7b15f92aea931774c4a28"

      def install
        bin.install "git-hooks"
        bash_completion.install "completions/foo.bash" => "foo"
      end
    end
    on_arm do
      url "https://github.com/lvrach/git-hooks/releases/download/v0.0.1-rc-5/git-hooks_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "a82bb93f8b46a5c9a2341ff1158b3b879094bd9cd408cdb1a4dbcf66e336efd7"

      def install
        bin.install "git-hooks"
        bash_completion.install "completions/foo.bash" => "foo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvrach/git-hooks/releases/download/v0.0.1-rc-5/git-hooks_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "9de721d65f3b24563b49804af4f6f731f91518745d0deb438f4643607ee75dec"

        def install
          bin.install "git-hooks"
          bash_completion.install "completions/foo.bash" => "foo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvrach/git-hooks/releases/download/v0.0.1-rc-5/git-hooks_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "2803c3581e579a3ec9ebda77a8ae79b2bd882b88697de23dba966b385b0dcb13"

        def install
          bin.install "git-hooks"
          bash_completion.install "completions/foo.bash" => "foo"
        end
      end
    end
  end

  test do
    system "#{bin}/git-hooks"
  end
end
